//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public int Id { get; set; }
        public Nullable<int> DzienTyg { get; set; }
        public Nullable<System.TimeSpan> GodzRozp { get; set; }
        public Nullable<System.TimeSpan> GodzZak { get; set; }
        public Nullable<int> IdProwadzacego { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
