//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Godziny = new HashSet<Godziny>();
            this.Plan = new HashSet<Plan>();
        }
    
        public int Id { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Tytul { get; set; }
        public string Instytut { get; set; }
        public string Email { get; set; }
        public string Haslo { get; set; }
    
        public virtual ICollection<Godziny> Godziny { get; set; }
        public virtual ICollection<Plan> Plan { get; set; }
    }
}
